#!/bin/bash
CUDA_VISIBLE_DEVICES=0 python main.py \
  --run_entity eibl-usc \
  --device 0 \
  --seed 0 \
  --mask_rate 0.5 \
  --dropout 0.0 \
  --drop_edge_rate 0.0 \
  --num_layers 1 \
  --lr 2e-5 \
  --weight_decay 0.01 \
  --lr_f 1e-2 \
  --cut_off 32 \
  --batch_size 8 \
  --eval_batch_size 64 \
  --num_epochs 2 \
  --num_roots 3 \
  --length 3 \
  --gnn_type gat \
  --lp_epochs 10 \
  --eval_steps 1 \
  --eval_interval 0 \
  --save_steps 1 \
  --save_interval 10000 \
  --hidden_size 128 \
  --lm_type prajjwal1/bert-tiny \
  --datasets_name FB15K237 \
  --eval_datasets_name FB15K237 \
  --process_mode TA \
  --lam 0.1
